#@ load("@ytt:data", "data")

---
apiVersion: authentication.concierge.pinniped.dev/v1alpha1
kind: JWTAuthenticator
metadata:
  name: tkg-jwt-authenticator
spec:
  #! The cascading controller will need to make sure this is set.
  audience: #@ data.values.pinniped.concierge.audience
  issuer: #@ data.values.pinniped.supervisor_svc_endpoint
  tls:
    certificateAuthorityData: #@ data.values.pinniped.supervisor_ca_bundle_data
